version: '3'
services:
  persochatta_backend:
    image: ghcr.io/avarios/persochatta_backend:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCES_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_DEFAULT_REGION}
    ports:
      - 5000:5000
  persochatta_frontend:
    image: ghcr.io/avarios/persochatta_frontend:latest
    environment:
      - PRIVATE_BACKEND_URL=http://persochatta_backend:5000
    ports:
      - 3000:3000