# Build stage
FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install typescript -g
RUN npm ci --only-production
COPY . .
RUN npm run build

# Production stage
FROM node:alpine
WORKDIR /app
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 5000
CMD ["npm", "run", "start:dist"]